using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using ProductManagement.Data;
using ProductManagement.Extensions;
using ProductManagement.Repositories;
using ProductManagement.Services;

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        // Add services to the container.

        builder.Services.AddControllers();
        builder.Services.AddDbContext<ProductContext>(options =>
            options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

        // Configure AutoMapper
        builder.Services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());

        // Register repositories and services
        builder.Services.AddScoped<IProductRepository, ProductRepository>();
        builder.Services.AddScoped<IProductService, ProductService>();
        builder.Services.AddScoped<IMixpanelService, MixpanelService>();


        // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
        builder.Services.AddEndpointsApiExplorer();

        builder.Services.AddSwaggerGenWithAuth(builder.Configuration);


        //JWT signature(generated by keycloak) = RSASign(privateKey, SHA256(Base64UrlEncode(header) + "." + Base64UrlEncode(payload)))
        //isValid(by backend app) = RSAVerify(publicKey, SHA256(header + "." + payload), signature)
        //verification process called Asymmetric Signature

        builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(o =>
            {
                o.RequireHttpsMetadata = false;
                o.Audience = builder.Configuration["Authentication:Audience"]!;
                o.MetadataAddress = builder.Configuration["Authentication:MetadataAddress"]!; // call the endpoint

                ///optinal
                o.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = builder.Configuration["Authentication:ValidIssuer"],
                    RoleClaimType = "roles",
                    NameClaimType = "preferred_username"
                };
            });


        var app = builder.Build();

        // Configure the HTTP request pipeline.
        if (app.Environment.IsDevelopment())
        {
            app.UseSwagger();
            app.UseSwaggerUI();
        }
        //enable Cors 
        app.UseCors(x => x.AllowAnyHeader().AllowAnyOrigin().AllowAnyMethod());

        app.UseHttpsRedirection();

        app.MapControllers();

        app.Run();
    }
}
