using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using ProductManagement.Data;
using ProductManagement.Repositories;
using ProductManagement.Services;

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        // Add services to the container.

        builder.Services.AddControllers();
        builder.Services.AddDbContext<ProductContext>(options =>
            options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

        // Configure AutoMapper
        builder.Services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());
        
        var memcachedHost = builder.Configuration["Memcached:Host"] ?? "127.0.0.1";
        var memcachedPort = int.Parse(builder.Configuration["Memcached:Port"] ?? "11211");
        builder.Services.AddEnyimMemcached(options =>
        {
            options.AddServer(memcachedHost, memcachedPort);
        });
        // Register repositories and services
        builder.Services.AddScoped<IProductRepository, ProductRepository>();
        builder.Services.AddScoped<IProductService, ProductService>();
        builder.Services.AddScoped<IMixpanelService, MixpanelService>();


        // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
        builder.Services.AddEndpointsApiExplorer();

        //Enable Swagger UI with Keycloak authentication
        //builder.Services.AddSwaggerGenWithAuth(builder.Configuration);
        builder.Services.AddSwaggerGen(option =>
        {
            option.SwaggerDoc("v1", new OpenApiInfo { Title = "Demo API", Version = "v1" });

            //Tells Swagger that your API uses Bearer token(JWT) authentication.
            //Adds the "Authorize" button to Swagger UI.
            //Describes how the client should send the token:
            //    In the Authorization header.
            //    With this format: Bearer<your_token_here>
            option.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
            {
                In = ParameterLocation.Header,
                Description = "Please enter a valid token",
                Name = "Authorization",
                Type = SecuritySchemeType.Http,
                BearerFormat = "JWT",
                Scheme = "Bearer"
            });

            //Applies the Bearer authentication scheme globally to all endpoints.
            //This means: Swagger will send the token you enter in "Authorize" to every request automatically.
            option.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type=ReferenceType.SecurityScheme,
                            Id="Bearer"
                        }
                    },
                    new string[]{}
                }
            });
        });

        //JWT signature(generated by keycloak) = RSASign(privateKey, SHA256(Base64UrlEncode(header) + "." + Base64UrlEncode(payload)))
        //isValid(by backend app) = RSAVerify(publicKey, SHA256(header + "." + payload), signature)
        //verification process called Asymmetric Signature

        builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(o =>
            {
                o.RequireHttpsMetadata = false;
                o.Audience = builder.Configuration["Authentication:Audience"]!;
                o.MetadataAddress = builder.Configuration["Authentication:MetadataAddress"]!; // call the endpoint

                ///optinal
                o.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = builder.Configuration["Authentication:ValidIssuer"],
                    RoleClaimType = "role",
                    NameClaimType = "preferred_username",
                    ValidateIssuerSigningKey = true,
                    ValidateLifetime = true
                };
            });
        builder.Services.AddAuthorization();
        builder.Services.AddScoped<IAuthorizationHandler, PermissionAuthorizationHandler>();
        builder.Services.AddSingleton<IAuthorizationPolicyProvider, PermissionAuthorizationPolicyProvider>();
        builder.Services.AddHttpClient();
        builder.Services.AddScoped<KeycloakAuthService>();
        var app = builder.Build();

        // Configure the HTTP request pipeline.
        if (app.Environment.IsDevelopment())
        {
            app.UseSwagger();
            app.UseSwaggerUI();
        }
        //enable Cors 
        app.UseCors(x => x.AllowAnyHeader().AllowAnyOrigin().AllowAnyMethod());
        app.UseEnyimMemcached();
        app.UseHttpsRedirection();

        app.MapControllers();

        app.Run();
    }
}
